M48
; DRILL file KiCad 10.0.0 date 2026-04-05T08:07:15
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-05T08:07:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.400
%
G90
G05
T1
X60.0Y-20.75
X60.0Y-24.25
T2
X3.5Y-10.0
X8.5Y-10.0
M30
